version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: go_shop_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go_shop_network

volumes:
  postgres_data:

networks:
  go_shop_network:
    driver: bridge
